### ISSUE TITLE
Publish to Hex package manager

### ISSUE THREAD

**Issue by waisbrot** [semiocast/pgsql#30]
Any interest in publishing pgsql to [Hex](https://hex.pm/)? It's a little more heavyweight than just tagging the Github releases, but I've been enjoying using Hex dependencies with Rebar3.

The Rebar tutorial on publishing to Hex: http://www.rebar3.org/v3.0/docs/publishing-packages

**Comment by waisbrot** [comment]
Bump. 

I'd be willing to manage the Hex release, if you're OK with it. (I'll make it available on Hex and update it when you perform new releases.) It is possible to give multiple accounts access, so it'd be easy to transfer/share control to anyone at semiocast at a later point.

**Comment by pguyot** [comment]
It seems Hex.pm does not like pgsql version string ("25").

===> Status Code: HTTP status code: 400
Hex Error: /tmp/build_a5dc7c83022b46f250ec3f0763b2246b/lib/hex_web/release.ex:187: value `"25"` in `where` cannot be cast to type HexWeb.Version in query:

from r in HexWeb.Release,
  where: r.package_id in ^[1135],
  where: r.version == ^"25",
  limit: 1

Error when casting value to `HexWeb.Release.version`

**Comment by tsloughter** [comment]
Yea, afraid it has to be a "semver" (just meaning it has to be something like `x.y.z`)

**Comment by pguyot** [comment]
Is there any rationale for this requirement?
Erlang allows any `string()`  for the version of an application, as per app(5).

**Comment by tsloughter** [comment]
It makes it easier to do comparisons if there is a known format. Hex uses http://elixir-lang.org/docs/stable/elixir/Version.html

Same goes for rebar3 which parses the package versions with https://github.com/erlware/erlware_commons/blob/master/src/ec_semver.erl

**Comment by tsloughter** [comment]
@pguyot any chance of pgsql updating to like `25.0.0` and publishing to hex?

**Comment by pguyot** [comment]
pgsql 26.0.0 is now on hex
https://hex.pm/packages/pgsql
