### ISSUE TITLE
JSON and JSONB support

### ISSUE THREAD

**Issue by rufrozen** [semiocast/pgsql#32]
Did you plan to add JSON and JSONB support?
For now to insert or update I need use this **($1::text)::jsonb**
And for select this **field::json** where I got raw json string as*\* {json, Json}*\* or raw jsonb as **{jsonb, JsonB}**

**Comment by tsloughter** [comment]
I have a PR for this https://github.com/semiocast/pgsql/pull/35 but the travis postgres seems to not support jsonb.

**Comment by pguyot** [comment]
Fixed with PR #42
