### ISSUE TITLE
Error responses as maps

### ISSUE THREAD

**Issue by tsloughter** [semiocast/pgsql#38]
Originally I had been matching on the error responses to get like the `code`, but then at some point the order changed for some reason and to keep from that hurting us again we use `keyfind` now everywhere after an error if we care what the error was.

A nice way to allow for pattern matching for this would be to return a map.

Would you be interested in such a change? I could put it behind a compile time configuration or runtime if you want to keep the default as a list of tuples.

**Comment by benjamin-bergia** [comment]
I have been playing with this myself https://github.com/benjamin-bergia/pgsql/blob/f2aecd8f7c27094e00e8dc988c996f4d3b9a262b/src/pgsql_protocol.erl#L696.
Would be nice to pass this setting as a query option like `return_descriptions`.

**Comment by pguyot** [comment]
Returning errors in a map would make sense with modern pattern matching on maps, and I am ok with dropping compatibility with Erlang R16. However, the error type ```pgsql_error:pgsql_error/0``` is not opaque, and changing it would break existing clients.

Consequently, I believe the best approach would be a runtime application environment option, with the default as list for now.

**Comment by tsloughter** [comment]
@benjamin-bergia were you going to make a PR of your changes?

**Comment by benjamin-bergia** [comment]
@tsloughter I wasn't planning to, but I can if you are interested.

**Comment by benjamin-bergia** [comment]
@pguyot Would this be fine? https://github.com/benjamin-bergia/pgsql/blob/return_errors_as_maps/src/pgsql_protocol.erl#L696-L702

**Comment by pguyot** [comment]
Yes, it sounds good. Thanks.
