### ISSUE TITLE
Proper way to monitor disconnections

### ISSUE THREAD

**Issue by benjamin-bergia** [semiocast/pgsql#39]
Might sound a little bit stupid, but is there any reliable way to be notified when a pgsql_connection get disconnected. I have tried `erlang:monitor/2` in combination with `{reconnect, false}`. But in cases where postgres terminate abruptly, the `pgsql_connection` process doesn't terminate.

**Comment by waisbrot** [comment]
Do you know if the TCP connection is being properly severed? If the server dies and nobody ever sends a RESET packet, then clients won't know the Postgres is dead until they send some request and then get an error or give up waiting for a response.

**Comment by benjamin-bergia** [comment]
No I don't think it is terminated properly. During my testing I was just killing the database instance.
So I guess that's why almost all the connection poolers have test queries such as "SELECT 1;" or "SELECT version();".
