### ISSUE TITLE
Confusing sentence in readme

### ISSUE THREAD

**Issue by cbaggers** [semiocast/pgsql#48]
I'm pretty new to erlang so this may just be me, but I find the following rather confusingly worded:

> For convenience with other database APIs, connection objects can be used as parametrized modules as connection objects are {pgsql_connection, pid()} tuples.

Does it mean this?

> For convenience with other database APIs, connection objects can be used as parametrized modules. Connection objects are {pgsql_connection, pid()} tuples.

**Comment by pguyot** [comment]
Thank you for your interest in pgsql.
Parametrized modules is (was) a hidden feature of Erlang language. With this sentence, we mostly mean that you can do the following:

    Connection = pgsql_connection:open(...),
    Result = Connection:simple_query("SELECT ..."),

and this is equivalent to:

    Connection = pgsql_connection:open(...),
    Result = pgsql_connection:simple_query("SELECT ...", Connection)

as if Connection was a "module", while it is a tuple `{pgsql_connection, pid()}`. Erlang runtime's remote call code works on both atoms (the module name, `pgsql_connection` in the second snippet) as well as on tuples where the first element is an atom. In this second case, it invokes the function with arity n+1 and passes the tuple as the last argument.

Parametrized module calls were used by very popular libraries such as [mochiweb](https://github.com/mochi/mochiweb).

Is the following version of the sentence clearer?

> Connection objects are `{pgsql_connection, pid()}` tuples. As a result, and following other database APIs, connection objects can be used as [parametrized modules](http://erlang.se/workshop/2003/paper/p29-carlsson.pdf).

**Comment by cbaggers** [comment]
Thanks for the excellent breakdown, and yup the new version is much clearer (at least to me).
