### ISSUE TITLE
Add an option to truncate timestamps to integers.

### ISSUE THREAD

**Issue by devinus** [semiocast/pgsql#7]
Is there a reason timestamps aren't returned in Erlang [timestamp() format](http://erlang.org/doc/man/erlang.html#type-timestamp)?

E.g.

``` iex
iex(6)> Ecto.Pool.query "SELECT NOW()"
{1,[{{{2013,3,21},{18,35,0.241573}}}]}
```

**Comment by pguyot** [comment]
The option is `{datetime_float_seconds, round | always | as_available}`. as_available is the default, returning integer timestamps when the number of microseconds is 0.
